### ISSUE TITLE
Update formula for BOD removed as FS

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#138]
The formula for [fsc_bod_rmvd ](http://84.89.61.64:8030/ecam/variable.php?id=fsc_bod_rmvd) is wrong. It should not devide by the density. 

![image](https://user-images.githubusercontent.com/33861734/45028851-ecb0a900-b046-11e8-9334-8566ac12278d.png)

The correct fomrula is as follows:

fsc_bod_rmvd  = fsc_fslu_emp * fsc_bod_conc_fs

**Comment by holalluis** [comment]
fixed

**Comment by Ranf16** [comment]
The formula is still wrong:
![image](https://user-images.githubusercontent.com/33861734/45075124-5cc23c00-b0e6-11e8-8bb6-fb7a454b53db.png)

It should multiply the two variables, not devide. So the formula is:

fsc_bod_rmvd = fsc_fslu_emp * fsc_bod_conc_fs

**Comment by holalluis** [comment]
ok, sorry, now it is correct
