### ISSUE TITLE
Compability with MS Edge and Firefox

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#23]
Please see here a short screencast video showing the issues when using ECAM with MS Edge: https://www.dropbox.com/s/r2p93v5juxx910j/Issues_with_MS_EDGE.webm?dl=0

**Comment by holalluis** [comment]
Dear Ranjin, 
Thank you, I've seen the video. I will have to install a virtual box with ms edge to test ecam there. So for now I'll list the bugs to be able to recall them later:
- In configuration, selecting the country does not display the country selected.
- In Tier A: selecting input boxes makes disappear digits
- In Tier B: fatal error in inputs & outputs table
- In Tier B: modifying a number moves the screen annoyingly

**Comment by holalluis** [comment]
Dear Ranjin,
I've improved some of the underlying code for compatibility. Could you test again the issues reported for MS Edge? I have not access to a computer with windows to test it.
Thanks,

**Comment by Ranf16** [comment]
Dear Lluis,

Note: Please first work on the other issues pointed out.

This issues still  exist, see this recent video that my collegue recorded after deleting browser cachée:

https://www.dropbox.com/s/4wtfkv9rpf5ziz7/ECAM-MS%20Edge_07.05.2018.mp4?dl=0

**Comment by holalluis** [comment]
Thank you for the video,
The problem should be solved I think, but I'm not sure because I don't have access from my computer to MS Edge.

**Comment by Ranf16** [comment]
Dear Lluis,

the following issue is still not fixed:

**Tier B: fatal error in inputs & outputs table**

Please see the video here: https://www.dropbox.com/s/087lhl84vo6rgqw/ECAM-MS%20May%2017.mp4?dl=0

**Comment by holalluis** [comment]
Try now, yesterday I found a non-compatible function I was using, and now I changed to a one which is compatible with all browsers. http://84.89.61.64:8030/ecam/

**Comment by Ranf16** [comment]
YES! It Works now!! The tables are showing. Great job. Thanks

There are however still the following issues:

1. Annoying bug: If you type in a value and hit enter key nothing happens. You need to click somewhere in order for it to accept the values you have typed in and when you do that the screen always jumps up to the top.

2. The opportunities page is not showing, see below:
![image](https://user-images.githubusercontent.com/33861734/40259745-b6ef1bf2-5af7-11e8-889d-54daa86d9f17.png)

I'd say for now, please focus on the reuse. If there is time at the end we can decide if we still need to fix the two issues mentioned above.

**Comment by holalluis** [comment]
Yes, I'm aware that opportunities is not working, this is because it was done by other programmer. This is something we should discuss in the future.

**Comment by holalluis** [comment]
It is the expected behaviour that when the user presses enter nothing happens. I changed this because helped me solving some other problems. We can improve this in the future.

**Comment by holalluis** [comment]
closing this. Please create a new issue for each problem if still exists if you test again with ms edge
