### ISSUE TITLE
Onsite Sanitation new filters /Dropdownmenu / possibility to cluster in input field?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#321]
Dear @holalluis , it was commented that the ### Onsite Sanitation was mixed and not clear.

Could you please rearrange the order to and replace the filters:

**General**
- Population   with onsite treatment | wwo_onsi_pop
- Population with open   defecation | wwo_open_pop
- Volume   of uncollected wastewater | wwo_vol_unco
- Do you   know the utility costs by stage? | Yes/no
- Evaluate   transport of faecal sludge? | Yes/no

**Containment**
- Influent   BOD load | wwo_bod_infl
- CH4 emission factor (treatment) | wwo_ch4_efac_tre
- Containments emptied | wwo_cont_emp
- Faecal   sludge emptied | wwo_fslu_emp
- BOD removed as faecal sludge | wwo_bod_rmvd
- Faecal sludge density | wwo_fdensity
- BOD concentration of faecal   sludge | wwo_bod_conc_fs
- Total Nitrogen load in the   influent | wwo_tn_infl
- Total Nitrogen load in the   effluent | wwo_tn_effl
- Is the containment   experiencing flooding or groundwater infiltration? | wwo_flooding

**Treatment**
- N2O emission factor (treatment) | wwo_n2o_efac_tre
- BOD removed with excess sludge | wwo_bod_slud
- Effluent BOD load | wwo_bod_effl
- CH4 emission factor (discharge of effluent) | wwo_ch4_efac_dis
- N2O emission factor (discharge of effluent) | wwo_n2o_efac_dis
- Are you producing biogas from   anaerobic digestion? | Yes/no

**Disposal / Enduse**
- Do you   want to assess landfilling of faecal sludge? | Yes/no
- Do you want to assess land   application of faecal sludge? | Yes/no
- Do you want to assess dumping   of faecal sludge? | Yes/no
- Do you want to assess land   application of urine? | Yes/no
- Do you want to assess GHG   avoided from reusing nutrients? | Yes/no

**Open Defecation**
- N2O emission factor (open   defecation) | wwo_n2o_efac_opd
- Protein   consumed by population with open defecation | wwo_prot_con

**Energy Consumption**
- Energy   consumed from the grid | wwo_nrg_cons
- Emission   factor for grid electricity | wwo_conv_kwh
- Do you have fuel engines? | Yes/no
- Do you want to evaluate   pumping efficiency? | Yes/no

@holalluis , is it possible to make a clear line between each of the clusters? This is a special case...since we have gathered all the information of 3 stages into one.

It would be great, if we could have drop down menues for each of those. Currently ...it's very long and you have to scroll down.

We can discuss this during one of our calls

**Comment by ElaChe00** [comment]
As discussed during our calls, include filters, but also rearrange the order a bit:

Filters (Inputs can be seen above in my posts)

- General
- Containment
- Treatment
- Disposal / Enduse
- Open Defecation
- Energy Performance

Remove the other filters (otherwise we have too many)

**Comment by holalluis** [comment]
Dear Elaine, this is done. Please check. I've added some variables in 2 filters (for example, "population with open defecation" is in "General" and also in "Open Defecation" filters), so the variable grouping is not exactly like the one you posted, but we can discuss the category of each one.

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/116469162-0f380600-a872-11eb-8ac7-98d8ee86c2e4.png)

done, please check

**Comment by ElaChe00** [comment]
Thanks. Definitely better!
Could you please put "**Biogas**" under **"Energy Performance"** Thanks!

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
Hey Lluis, I have emptied the cache, but I still see Biogas seperately in

"Treatment and" "Onsite". Since this is only one small question, it should go under Energy Performance

![image](https://user-images.githubusercontent.com/45791540/117619250-52964c80-b16f-11eb-9e78-4cb5d18735c7.png)

![image](https://user-images.githubusercontent.com/45791540/117619217-43170380-b16f-11eb-8ef9-f8ed60514d58.png)

**Comment by holalluis** [comment]
Ah, I'm sorry, I understood "under" as "after". Do you want to remove the "Biogas" filter, right?

**Comment by ElaChe00** [comment]
My bad, I should've been clearer. 

Yes, please remove the biogas filter. Biogas should be part of energy performance :)

**Comment by holalluis** [comment]
done, please check
