### ISSUE TITLE
More | Tables -> Please adapt labels

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#410]
Adapt spelling to unify the labels

![image](https://user-images.githubusercontent.com/45791540/121708291-b6e25e00-cad7-11eb-92b0-b4cae1728713.png)

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
One is still not adapted:

![image](https://user-images.githubusercontent.com/45791540/122007559-55144380-cdb8-11eb-8a86-bc01f7970062.png)

**Comment by holalluis** [comment]
done please check
